services:
  local_dev_atlas:
    image: mongodb/mongodb-atlas-local:8.0
    hostname: local_dev_atlas
    ports:
      - 27017:27017
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=philoagents
      - MONGODB_INITDB_ROOT_PASSWORD=philoagents
    volumes:
      - data:/data/db
      - config:/data/configdb
    networks:
      - philoagents-network

  postgres:
    image: postgres:15-alpine
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=philoagents_multiplayer
      - POSTGRES_USER=philoagents
      - POSTGRES_PASSWORD=philoagents
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - philoagents-network
  api:
    container_name: philoagents-api
    build:
      context: ./philoagents-api
      dockerfile: Dockerfile.local
    environment:
      - MONGO_URI=mongodb://philoagents:philoagents@local_dev_atlas:27017/?directConnection=true
    ports:
      - "8000:8000"
    env_file:
      - ./philoagents-api/.env
    volumes:
      - ./philoagents-api/src/philoagents:/app/philoagents
      - ./philoagents-api/tools:/app/tools
    networks:
      - philoagents-network
  multiplayer:
    container_name: philoagents-multiplayer
    build:
      context: ./philoagents-multiplayer
      dockerfile: Dockerfile.local
    ports:
      - "2567:2567"
    environment:
      - NODE_ENV=development
      - PORT=2567
      - CORS_ORIGIN=http://localhost:3000,http://localhost:8080
      - DATABASE_URL=postgresql://philoagents:philoagents@postgres:5432/philoagents_multiplayer
      - ENABLE_MONITOR=true
      - ENABLE_PLAYGROUND=true
      - MAX_PLAYERS_PER_ROOM=10
      - WORLD_WIDTH=1600
      - WORLD_HEIGHT=1200
      - SPAWN_RADIUS=200
      - INACTIVE_TIMEOUT_MS=300000
      - PHILOAGENTS_API_URL=http://api:8000
    volumes:
      - ./philoagents-multiplayer/src:/app/src
      - ./philoagents-multiplayer/lib:/app/lib
    depends_on:
      postgres:
        condition: service_started
    networks:
      - philoagents-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2567/health"]
      interval: 30s
      timeout: 10s
      retries: 3

# Next.js UI runs locally via npm run dev (port 3000)
  # Use: cd philoagents-nextjs && npm run dev

  # Legacy Phaser.js game UI (uncomment if needed separately)
  # game-ui:
  #   container_name: philoagents-game-ui
  #   build:
  #     context: ./philoagents-ui
  #     dockerfile: Dockerfile.local
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./philoagents-ui:/app
  #     - /app/node_modules
  #   depends_on:
  #     - api
  #     - multiplayer
  #   networks:
  #     - philoagents-network

volumes:
  data:
  config:
  postgres_data:

networks:
  philoagents-network:
    name: philoagents-network